dist: trusty
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: KQGR9/C+xK7qaErUxSW3qA7KomfEPBxR3bbrpKi0ctbrEaSUiLKwL7Jv1GomEXSGCO+fyrcjf+h/P9P0JUhGRLX7mm3fkWz2XIUiLQZ7qJiXAxdIAB3rzrTKzQRjWIaVqycbihuqsQZtIVvyN7dj2nNBatBWC114ErNHtk4sEa0zTUIlo0gfEQhkBbyrHNgNI3LLVcCML+F4Dzw1Kezz/Ykgc7RxU/elyXEvTPZPt5mZaSHtGm6qjVfA3zEhWPFS5/LLySxgSwmV0GcNq9wxg7il91yRl3kYMa/dWUaihcdC92231ao7XyfrXwKG0Zng4vGu/9RSXJE99eIq4qo+J4fOKg72aOopRGj467XosjF4j7rhnOfGLhygr/mWcEVl76lH8Ctk6D0PkJw0pDMXyRdBabaeQSSOLYCEQtACG6ivwPVs89YS9+ZOLjEzIBihXlxveWvEddxt1XueoLyzav5E192BhhPfWbbIChxflKVgcyZJQfdWdcoldzvNejkloF3vcarKZt1LMyLz7ZvjldLu6daOz6ZTAQTsJciycE15Uk4LyK/D+9pqWqRrx/yqa5x6ZSqUj0SYaHfkVa9woDyJXstFjSG6HGzWV4XMKmpo2fLIG6loOlE9vEn4pvo3jZVtULooyxhVhcb8pXtYRxxIe+/LfMZ7nKb5IGB8sds=
